# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 12 hours
    - cron: "0 */12 * * *"

# This command allows us to run the Action automatically from the Actions tab.
workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v4

      # Generate the snake and set environment variables using an environment file
      - name: Generate the snake and set environment variables
        id: snake-gif
        run: |
          echo "GITHUB_USER_NAME=ChaitanyaC22" >> $GITHUB_ENV
          echo "GIF_OUT_PATH=dist/github-contribution-grid-snake.gif" >> $GITHUB_ENV
          echo "SVG_OUT_PATH=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV

      # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Use environment variables for crazy-max/ghaction-github-pages action
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIF_OUT_PATH: ${{ env.GIF_OUT_PATH }}
          SVG_OUT_PATH: ${{ env.SVG_OUT_PATH }}
          GITHUB_USER_NAME: ${{ env.GITHUB_USER_NAME }}
