name: Generate Snake
on:
  schedule: # execute every 12 hours
    - cron: "*/12 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Use Node.js version 16
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Snake Animation
      - name: Generate Snake GIF
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ChaitanyaC22
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Use Node.js version 16 for GitHub Pages action
      - name: Use Node.js 16.x for GitHub Pages
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Set output using environment file
      - name: Set output using environment file
        run: echo "SNAKE_GIF_PATH=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV
